language: c
compiler:
  - gcc
  - clang
script: make

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "iZ1KIL71+t+XHQOaOkuRDDvtUoQtvMciKI+U8u9r20dz1C+sdlMNt39e0NBvfA5iLj2mo9QaTVNsf31OucfmykSkbB7adFWsYx/11BdVd2t2PYjb3n07GJjDSodfo/8l3rrglkcB8ewYK37JImvRBQuJVn6MmpU32eZweo73c5o="

addons:
  coverity_scan:
    project:
      name: "lh3/bwa"
      description: "Build submitted via Travis CI"
    notification_email: lh3@me.com
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: dev
